name: test-action
on: push

jobs:
  test_job:
    name: Test Job
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_CREDENTIALS_CICD }}
        export_default_credentials: true

    - name: Use gcloud CLI
      run: gcloud info
      