name: push-action
on: push

jobs:
  plan_job:
    name: Plan Job
    runs-on: ubuntu-latest
    environment: feature
    env:
      PROJECT: ${{ secrets.GCP_PROJECT_ID }}

    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.RO_KEY }}
        export_default_credentials: true

    - name: Show logged in user
      run: gcloud config list

    - name: Terraform init
      run: echo "terraform plan"

    - name: Terraform plan
      run: echo "terraform plan"

  apply_job:
    name: Apply Job
    needs: plan_job
    runs-on: ubuntu-latest
    environment: feature
    env:
      PROJECT: ${{ secrets.GCP_PROJECT_ID }}

    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.RW_KEY }}
        export_default_credentials: true

    - name: Show logged in user
      run: gcloud config list

    - name: Terraform apply
      run: echo "terraform apply"

