name: push-to-master-action
on: 
  push:
    branches:
    - master

jobs:
  apply_job:
    name: Terraform apply (push to master)
    needs: plan_job
    runs-on: ubuntu-latest

    environment: master
    env:
      PROJECT: ${{ secrets.GCP_PROJECT_ID }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Cloud SDK - R/W account
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.RW_KEY }}
        export_default_credentials: true

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.5

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve
