name: test-action
on: push

jobs:
  test_job:
    name: Test Job
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      RW_SA: terraform-rw@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
      RO_SA: terraform-ro@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

    steps:
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_CREDENTIALS_CICD }}
        export_default_credentials: true

    - name: Use gcloud CLI
      run: gcloud info

    - name: Create R/O key
      run: |
        RO_KEY=$(gcloud iam service-accounts keys create - --iam-account=${RO_SA} ; rm -f -)
        echo RO_KEY=$RO_KEY >> $GITHUB_ENV
    
    # - name: Authenticate as R/O account
    #   uses: google-github-actions/setup-gcloud@master
    #   with:
    #     project_id: ${{ secrets.GCP_PROJECT_ID }}
    #     service_account_key: ${{ env.RO_KEY }}
    #     export_default_credentials: true

    # - name: gcloud config list
    #   run: gcloud config list

    - name: Do some terraform
      run: echo "some terraform"

    - name: Delete key
      run: echo $RO_KEY ; echo $RO_KEY | jq '.private_key_id'